apiVersion: v1
kind: Service
metadata:
  name: slightly-impulsive-service
spec:
  type: LoadBalancer
  selector:
    app: slightly-impulsive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
